baseURL = "https://srividyasuresh.github.io/toEchoTheWorld/"
languageCode = "en-us"
title = "To Echo The World"
theme = "bear"
publishDir = "public"

[params]
  author = "Srividya Suresh"
  description = "Blogs and some such"

[menu]

  [[menu.main]]
  identifier = "home"
  name = "Home"
  url = "/"
  weight = 1

  [[menu.main]]
  identifier = "techtalk"
  name = "Tech talk"
  url = "/techtalk/"
  weight = 2

  [[menu.main]]
  identifier = "thoughts"
  name = "Thoughts"
  url = "/thoughts/"
  weight = 3

  [[menu.main]]
  identifier = "moments"
  name = "Moments"
  url = "/moments/"
  weight = 4